/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppPointRulesRouteImport } from './routes/_app.point-rules'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppAlliesRouteImport } from './routes/_app.allies'
import { Route as AppMembersMemberIdRouteImport } from './routes/_app.members_.$memberId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppPointRulesRoute = AppPointRulesRouteImport.update({
  id: '/point-rules',
  path: '/point-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppAlliesRoute = AppAlliesRouteImport.update({
  id: '/allies',
  path: '/allies',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersMemberIdRoute = AppMembersMemberIdRouteImport.update({
  id: '/members_/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/allies': typeof AppAlliesRoute
  '/members': typeof AppMembersRoute
  '/point-rules': typeof AppPointRulesRoute
  '/login': typeof AuthLoginRoute
  '/members/$memberId': typeof AppMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/allies': typeof AppAlliesRoute
  '/members': typeof AppMembersRoute
  '/point-rules': typeof AppPointRulesRoute
  '/login': typeof AuthLoginRoute
  '/members/$memberId': typeof AppMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/allies': typeof AppAlliesRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/point-rules': typeof AppPointRulesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/members_/$memberId': typeof AppMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allies'
    | '/members'
    | '/point-rules'
    | '/login'
    | '/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allies'
    | '/members'
    | '/point-rules'
    | '/login'
    | '/members/$memberId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/allies'
    | '/_app/members'
    | '/_app/point-rules'
    | '/_auth/login'
    | '/_app/'
    | '/_app/members_/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/point-rules': {
      id: '/_app/point-rules'
      path: '/point-rules'
      fullPath: '/point-rules'
      preLoaderRoute: typeof AppPointRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/allies': {
      id: '/_app/allies'
      path: '/allies'
      fullPath: '/allies'
      preLoaderRoute: typeof AppAlliesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members_/$memberId': {
      id: '/_app/members_/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AppMembersMemberIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlliesRoute: typeof AppAlliesRoute
  AppMembersRoute: typeof AppMembersRoute
  AppPointRulesRoute: typeof AppPointRulesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMembersMemberIdRoute: typeof AppMembersMemberIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlliesRoute: AppAlliesRoute,
  AppMembersRoute: AppMembersRoute,
  AppPointRulesRoute: AppPointRulesRoute,
  AppIndexRoute: AppIndexRoute,
  AppMembersMemberIdRoute: AppMembersMemberIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
