/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthResetRouteImport } from './routes/_auth.reset'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AppPositionsRouteImport } from './routes/_app.positions'
import { Route as AppPointRulesRouteImport } from './routes/_app.point-rules'
import { Route as AppPermisosRouteImport } from './routes/_app.permisos'
import { Route as AppNotificacionesRouteImport } from './routes/_app.notificaciones'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppInitiativesRouteImport } from './routes/_app.initiatives'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppAlliesRouteImport } from './routes/_app.allies'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'
import { Route as AppMembersMemberIdRouteImport } from './routes/_app.members_.$memberId'
import { Route as AppActivitiesIdRouteImport } from './routes/_app.activities_.$id'
import { Route as AppInitiativesTypeIdRouteImport } from './routes/_app.initiatives_.$type.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppPointRulesRoute = AppPointRulesRouteImport.update({
  id: '/point-rules',
  path: '/point-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppPermisosRoute = AppPermisosRouteImport.update({
  id: '/permisos',
  path: '/permisos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInitiativesRoute = AppInitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppAlliesRoute = AppAlliesRouteImport.update({
  id: '/allies',
  path: '/allies',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersMemberIdRoute = AppMembersMemberIdRouteImport.update({
  id: '/members_/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesIdRoute = AppActivitiesIdRouteImport.update({
  id: '/activities_/$id',
  path: '/activities/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInitiativesTypeIdRoute = AppInitiativesTypeIdRouteImport.update({
  id: '/initiatives_/$type/$id',
  path: '/initiatives/$type/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activities': typeof AppActivitiesRoute
  '/allies': typeof AppAlliesRoute
  '/config': typeof AppConfigRoute
  '/initiatives': typeof AppInitiativesRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/leads': typeof AppLeadsRoute
  '/me': typeof AppMeRoute
  '/members': typeof AppMembersRoute
  '/notificaciones': typeof AppNotificacionesRoute
  '/permisos': typeof AppPermisosRoute
  '/point-rules': typeof AppPointRulesRoute
  '/positions': typeof AppPositionsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset': typeof AuthResetRoute
  '/activities/$id': typeof AppActivitiesIdRoute
  '/members/$memberId': typeof AppMembersMemberIdRoute
  '/initiatives/$type/$id': typeof AppInitiativesTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/activities': typeof AppActivitiesRoute
  '/allies': typeof AppAlliesRoute
  '/config': typeof AppConfigRoute
  '/initiatives': typeof AppInitiativesRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/leads': typeof AppLeadsRoute
  '/me': typeof AppMeRoute
  '/members': typeof AppMembersRoute
  '/notificaciones': typeof AppNotificacionesRoute
  '/permisos': typeof AppPermisosRoute
  '/point-rules': typeof AppPointRulesRoute
  '/positions': typeof AppPositionsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset': typeof AuthResetRoute
  '/activities/$id': typeof AppActivitiesIdRoute
  '/members/$memberId': typeof AppMembersMemberIdRoute
  '/initiatives/$type/$id': typeof AppInitiativesTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/allies': typeof AppAlliesRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/initiatives': typeof AppInitiativesRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/me': typeof AppMeRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/notificaciones': typeof AppNotificacionesRoute
  '/_app/permisos': typeof AppPermisosRoute
  '/_app/point-rules': typeof AppPointRulesRoute
  '/_app/positions': typeof AppPositionsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset': typeof AuthResetRoute
  '/_app/': typeof AppIndexRoute
  '/_app/activities_/$id': typeof AppActivitiesIdRoute
  '/_app/members_/$memberId': typeof AppMembersMemberIdRoute
  '/_app/initiatives_/$type/$id': typeof AppInitiativesTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/allies'
    | '/config'
    | '/initiatives'
    | '/leaderboard'
    | '/leads'
    | '/me'
    | '/members'
    | '/notificaciones'
    | '/permisos'
    | '/point-rules'
    | '/positions'
    | '/forgot-password'
    | '/login'
    | '/reset'
    | '/activities/$id'
    | '/members/$memberId'
    | '/initiatives/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/allies'
    | '/config'
    | '/initiatives'
    | '/leaderboard'
    | '/leads'
    | '/me'
    | '/members'
    | '/notificaciones'
    | '/permisos'
    | '/point-rules'
    | '/positions'
    | '/forgot-password'
    | '/login'
    | '/reset'
    | '/activities/$id'
    | '/members/$memberId'
    | '/initiatives/$type/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/activities'
    | '/_app/allies'
    | '/_app/config'
    | '/_app/initiatives'
    | '/_app/leaderboard'
    | '/_app/leads'
    | '/_app/me'
    | '/_app/members'
    | '/_app/notificaciones'
    | '/_app/permisos'
    | '/_app/point-rules'
    | '/_app/positions'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset'
    | '/_app/'
    | '/_app/activities_/$id'
    | '/_app/members_/$memberId'
    | '/_app/initiatives_/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/reset': {
      id: '/_auth/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/point-rules': {
      id: '/_app/point-rules'
      path: '/point-rules'
      fullPath: '/point-rules'
      preLoaderRoute: typeof AppPointRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permisos': {
      id: '/_app/permisos'
      path: '/permisos'
      fullPath: '/permisos'
      preLoaderRoute: typeof AppPermisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones': {
      id: '/_app/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/initiatives': {
      id: '/_app/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof AppInitiativesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/allies': {
      id: '/_app/allies'
      path: '/allies'
      fullPath: '/allies'
      preLoaderRoute: typeof AppAlliesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members_/$memberId': {
      id: '/_app/members_/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AppMembersMemberIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities_/$id': {
      id: '/_app/activities_/$id'
      path: '/activities/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof AppActivitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/initiatives_/$type/$id': {
      id: '/_app/initiatives_/$type/$id'
      path: '/initiatives/$type/$id'
      fullPath: '/initiatives/$type/$id'
      preLoaderRoute: typeof AppInitiativesTypeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppAlliesRoute: typeof AppAlliesRoute
  AppConfigRoute: typeof AppConfigRoute
  AppInitiativesRoute: typeof AppInitiativesRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMeRoute: typeof AppMeRoute
  AppMembersRoute: typeof AppMembersRoute
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppPermisosRoute: typeof AppPermisosRoute
  AppPointRulesRoute: typeof AppPointRulesRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppActivitiesIdRoute: typeof AppActivitiesIdRoute
  AppMembersMemberIdRoute: typeof AppMembersMemberIdRoute
  AppInitiativesTypeIdRoute: typeof AppInitiativesTypeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppAlliesRoute: AppAlliesRoute,
  AppConfigRoute: AppConfigRoute,
  AppInitiativesRoute: AppInitiativesRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMeRoute: AppMeRoute,
  AppMembersRoute: AppMembersRoute,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppPermisosRoute: AppPermisosRoute,
  AppPointRulesRoute: AppPointRulesRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppActivitiesIdRoute: AppActivitiesIdRoute,
  AppMembersMemberIdRoute: AppMembersMemberIdRoute,
  AppInitiativesTypeIdRoute: AppInitiativesTypeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
