import { describe, it, expect } from "vitest";
import {
  ACTIONS,
  SUBJECTS,
  ALL_PERMISSION_CODES,
  isValidPermissionCode,
  PERMISSION_CAP,
} from "./permission.js";
import { ROLES } from "./permission-role.js";

// Firebase caps the entire custom-claims payload at 1000 bytes. The `perms` claim a
// member carries is `{ roles, perms }`, and PERMISSION_CAP bounds perms.length so the
// serialized claim fits. Assert that real constraint from the real vocabulary — not the
// magic number — so bumping the cap can only pass if the worst-case claim still fits.
const FIREBASE_CLAIMS_BYTE_LIMIT = 1000;

describe("permission vocabulary", () => {
  it("accepts well-formed codes", () => {
    expect(isValidPermissionCode("manage:Member")).toBe(true);
    expect(isValidPermissionCode("read:Lead")).toBe(true);
    expect(isValidPermissionCode("manage:all")).toBe(true);
    expect(isValidPermissionCode("checkIn:Attendance")).toBe(true);
  });

  it("rejects malformed or unknown codes", () => {
    expect(isValidPermissionCode("bogus:Member")).toBe(false);
    expect(isValidPermissionCode("manage:Nope")).toBe(false);
    expect(isValidPermissionCode("manage")).toBe(false);
    expect(isValidPermissionCode(42)).toBe(false);
    expect(isValidPermissionCode(null)).toBe(false);
  });

  it("enumerates every action×subject without duplicates", () => {
    expect(ALL_PERMISSION_CODES.length).toBe(ACTIONS.length * SUBJECTS.length);
    expect(new Set(ALL_PERMISSION_CODES).size).toBe(ALL_PERMISSION_CODES.length);
  });

  it("keeps the worst-case perms claim within Firebase's 1000-byte limit", () => {
    const longestCode = ALL_PERMISSION_CODES.reduce((a, b) => (b.length > a.length ? b : a));
    // Worst case: a member holding every role, with a full cap of the longest code.
    const worstCaseClaim = {
      roles: [...ROLES],
      perms: Array<string>(PERMISSION_CAP).fill(longestCode),
    };
    const bytes = Buffer.byteLength(JSON.stringify(worstCaseClaim), "utf8");
    expect(bytes).toBeLessThan(FIREBASE_CLAIMS_BYTE_LIMIT);
  });
});

describe("Showcase subject", () => {
  it("is a known subject", () => {
    expect(SUBJECTS).toContain("Showcase");
  });
  // Only update:Showcase is read by firestore.rules' canCurateFeatured(); the other five
  // are generated by the cross-product and gate nothing. They must still be VALID codes —
  // the /permisos matrix renders the full grid, and an assignable-but-unvalidatable code
  // would fail the role editor's write validation.
  it("accepts update:Showcase and the inert siblings the matrix will render", () => {
    expect(isValidPermissionCode("update:Showcase")).toBe(true);
    expect(isValidPermissionCode("manage:Showcase")).toBe(true);
    expect(isValidPermissionCode("read:Showcase")).toBe(true);
  });
});

describe("BoardSeat subject", () => {
  it("is a known subject", () => {
    expect(SUBJECTS).toContain("BoardSeat");
  });
  // Same shape as Showcase: only update:BoardSeat is read (firestore.rules' boardSeatDelegate,
  // beacon's resolveTrustedGrants, backstage's canAssignBoardSeat). The siblings gate nothing
  // but must stay VALID — the /permisos matrix renders the full grid and the per-member
  // override panel offers every code, so an unvalidatable one would fail the write.
  it("accepts update:BoardSeat and the inert siblings the matrix will render", () => {
    expect(isValidPermissionCode("update:BoardSeat")).toBe(true);
    expect(isValidPermissionCode("manage:BoardSeat")).toBe(true);
    expect(isValidPermissionCode("read:BoardSeat")).toBe(true);
  });
});

describe("MemberLogin subject", () => {
  it("is a known subject", () => {
    expect(SUBJECTS).toContain("MemberLogin");
  });
  it("accepts create:MemberLogin and the inert siblings the matrix will render", () => {
    expect(isValidPermissionCode("create:MemberLogin")).toBe(true);
    expect(isValidPermissionCode("manage:MemberLogin")).toBe(true);
    expect(isValidPermissionCode("read:MemberLogin")).toBe(true);
  });
});

describe("Notification subject", () => {
  it("is a known subject", () => {
    expect(SUBJECTS).toContain("Notification");
  });
  it("accepts create:Notification and read:Notification", () => {
    expect(isValidPermissionCode("create:Notification")).toBe(true);
    expect(isValidPermissionCode("read:Notification")).toBe(true);
  });
});
